name: Refresh hashing salt

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  refresh-salt:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh hashing salt
        run: "curl
          --silent
          --verbose
          --header \"Content-Type: application/json\"
          --request POST
          --data \"{ \\\"token\\\": \\\"${TOKEN}\\\" }\"
          https://basilytics.vercel.app/api/refresh-salt"
        env:
          TOKEN: ${{ secrets.REFRESH_SALT_TOKEN }}
